### ISSUE TITLE
Rename SitemapUrlProvider

### ISSUE THREAD

**Issue by oriodesign** [apperclass/sitemap-bundle#10]
Maybe it's better rename SitemapUrlProvider as SitemapBuilder. Sitemap builder is responsible for adding Url, Video and Images to sitemap.

**Comment by hal9087** [comment]
I think SitemapBuilder must replace the SitemapGenerator, the SitemapUrlProviderInterface must become SitemapPopulatorInterface, the SitemapProvider must be removed

so...

```php

interface SitemapBuilder 
{

   /**
    * @param SitemapPopulatorInterface
    */
    public function addPopulator(SitemapPopulatorInterface $sitemapPopulator);
     
    /**
     * @return SitemapInterface
     */
    public function build();
}
```

```php

interface SitemapPopulatorInterface
{
   /**
    * @param SitemapInterface 
    */
    public function populate(SitemapInterface $sitemap);
}


so the directory/namespace layout of the Sitemap Package become:

```
Sitemap/
    Encoder/
    Model/
    Writer/
    SitemapBuilderInterface.php
    SitemapBuilder.php
    SitemapPopulatorInterface.php
```

**Comment by hal9087** [comment]
@oriodesign take a look at this pull request: https://github.com/apperclass/sitemap-bundle/pull/11

**Comment by hal9087** [comment]
@oriodesign take a look to this pull request: https://github.com/apperclass/sitemap-bundle/pull/12
